# Generated by Django 2.2.24 on 2021-10-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=False)),
                ('schedule', models.CharField(max_length=200)),
            ],
        ),
    ]
